### ISSUE TITLE
Book Recommendations?

### ISSUE THREAD

**Issue by abi-aryan** [abi-aryan/psych-neuro-cs#8]
What do you think are some of the most excellent reading recommendations on the subject?

**Comment by pragyakale** [comment]
Should books with interesting case studies which let us learn about psychology and neuroscience be added?

**Comment by abi-aryan** [comment]
Could you list a few examples maybe?

**Comment by pragyakale** [comment]
Books like 
[The Man Who Mistook His Wife for a Hat and Other Clinical Tales](https://www.goodreads.com/book/show/63697.The_Man_Who_Mistook_His_Wife_for_a_Hat_and_Other_Clinical_Tales)
[Phantoms in the Brain: Probing the Mysteries of the Human Mind](https://www.goodreads.com/book/show/31555.Phantoms_in_the_Brain)

**Comment by abi-aryan** [comment]
Oh, yeah I've heard good things about both of them. They can go under [Fiction](https://github.com/abi-aryan/psych-neuro-cs#good-reads) in Good Reads.

**Comment by reshusinghhh** [comment]
Blink: The Power of Thinking Without Thinking
by Malcolm Gladwell
https://www.goodreads.com/book/show/40102.Blink?ac=1&from_search=true

**Comment by abi-aryan** [comment]
@reshusinghhh I am not too sure if I would keep Blink in there. Gladwell has a reputation for misquoting case studies often. Something he did with his book Outliers as well and 10,000 hours to success. I only partially read Blink a couple of years ago and while his take is interesting I am afraid, it's not scientifically sound. 

Let's find some others to add in there.

**Comment by angelagilhotra** [comment]
@abi-aryan I'm confused, why is the book "Phantoms in the Brain" by VS Ramachandran under Fiction?

**Comment by abi-aryan** [comment]
As my reading of the book goes, the author of "Phantoms in the Brain" takes us through the stories of 13 of his patients - surely ain't a fiction but not a compulsory reading either - probably better placed among case studies. Thanks for noticing though and very sorry for the late response.

**Comment by abi-aryan** [comment]
Classify these books into sub-categories-

1. Gibson, James J: An Ecological Approach to Visual Perception
2. Goldberg, Elkhonon: The New Executive Brain
3. Gray, Jeffrey and Neil McNaughton: The Neuropsychology of Anxiety
4. LeDoux, Joseph: The Emotional Brain
5. Panksepp, Jaak: Affective Neuroscience
6. Sacks, Oliver: The Man who Mistook his Wife for a Hat
7. Sacks, Oliver: Awakenings
8. Sacks, Oliver: An Anthropologist on Mars
9. Swanson, Larry: Brain Architecture: Understanding the Basic Plan
